
<!--Użytkownik podaje w formularzu imie, nazwisko, wiek i narodowość. Sprawdź czy przesłał wszystkie dane, jeśli tak to wyświetl mu na stronie cookieSuccess.php komunikat przesłany zmienną sesyjną o treści prawidłowo przesłany formularz * Imie i nazwisko przypisz od zmiennych sesyjnych wiek i narodowość przypisz do zmiennej Cookie
Wyświetl dane na stronie: cookieSuccess.php w formacie:
Imię i nazwisko:...
Wiek: ...
Narodowość: ...
Zabezpiecz fomularz przed podaniem danych, które będą miały więcej niż 10 znaków, w przypadku błedów wyświetl za pomocą zmiennej sesyjnej komunikat pod formularzem
-->
